pull_request_rules:
  - name: automatic merge when GitHub branch protection passes on master
    conditions:
      - author=PeteBishwhip
      - status-success=continuous-integration/travis-ci/pr
      - base=master
    actions:
      merge:
        method: merge
        
pull_request_rules:
  - name: automatic merge when GitHub branch protection passes on master
    conditions:
      - author=ODSMarcus
      - status-success=continuous-integration/travis-ci/pr
      - base=master
    actions:
      merge:
        method: merge
        
pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
      
      
