pull_request_rules:
  - name: automatic merge when GitHub branch protection passes on master
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - base=master
    actions:
      merge:
        method: merge