language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - curl https://whmcs.peterbishop.rocks/apiAllowIP.php
  - vendor/bin/phpunit tests
